from django.urls import path
from . import views

app_name = 'muddata'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/<int:wellphase_id>/', views.create, name='create'),
    path('list/<int:wellphase_id>/', views.list, name='list'),
    path('edit/<int:well_phase_id>/', views.edit, name='edit'),
    path('delete/<int:well_phase_id>/', views.delete, name='delete'),
    path('rheogramcreate/<int:wellphase_id>/', views.rheogramcreate, name='rheogramcreate'),
    path('<int:pk>/', views.rheogramdetails, name='rheogramdetails'),
    path('rheogramedit/<int:pk>/', views.rheogramedit, name='rheogramedit'),
    path('rheogramdelete/<int:pk>/', views.rheogramdelete, name='rheogramdelete'),
    path('rheogramlist/<int:wellphase_id>/', views.rheogramlist, name='rheogramlist'),
    path('muddata_value',views.muddata_value,name='muddata_value'),
    path('storewellphase_session',views.storewellphase_session,name='storewellphase_session'),
    path('getstorewellphase',views.getstorewellphase,name='getstorewellphase'),
    path('getrheogramrpm',views.getrheogramrpm,name='getrheogramrpm'),
    path('gethydraulicsmenu/<int:well_id>/',views.gethydraulicsmenu,name='gethydraulicsmenu'),
    path('getwellphasemenubyid/<int:wellphase_id>/',views.getwellphasemenubyid,name='getwellphasemenubyid'),
    path('insertmudtype',views.insertmudtype,name='insertmudtype'),
    path('getdialrpm',views.getdialrpm,name='getdialrpm'),
    path('get_bingham_plastic',views.get_bingham_plastic,name='get_bingham_plastic'),
    path('getdirectchart',views.getdirectchart,name='getdirectchart'),
    path('getrheogrammodals',views.getrheogrammodals,name='getrheogrammodals'),
    path('get_porepressure_md',views.get_porepressure_md,name='get_porepressure_md'),
    path('calculatedial',views.calculatedial,name='calculatedial'),
    path('muddatarheogramlist/<int:wellphase_id>/',views.muddatarheogramlist,name='muddatarheogramlist'),
    path('modelselected',views.modelselected,name='modelselected'),
    path('pressurelawcalculation/<int:wellphase_id>/',views.pressurelawcalculation,name='pressurelawcalculation'),
    path('annuluspressureloss/<int:wellphase_id>/',views.annuluspressureloss,name='annuluspressureloss'),
    path('calculateallpressureloss/<int:wellphase_id>/',views.calculateallpressureloss,name='calculateallpressureloss'),
    path('calculateallpressure_loss',views.calculateallpressure_loss,name='calculateallpressure_loss'),
    path('calculatepressureloss',views.calculatepressureloss,name='calculatepressureloss'),
    path('displayallmodals',views.displayallmodals,name='displayallmodals'),
    path('checkmudmotor',views.checkmudmotor,name='checkmudmotor'),
    path('calculatesensitivity',views.calculatesensitivity,name='calculatesensitivity'),
    path('getallmodels',views.getallmodels,name='getallmodels'),
    path('allmodel_surface',views.allmodel_surface,name='allmodel_surface'),
    path('allmodel_annular',views.allmodel_annular,name='allmodel_annular'),
    path('getsectionrange',views.getsectionrange,name='getsectionrange'),
    path('getoptimization/<int:well_id>/',views.getoptimization,name='getoptimization'),
    path('calculatenewoptimization',views.calculatenewoptimization,name='calculatenewoptimization'),
    path('hydraulicdata/<int:wellphase_id>/',views.hydraulicdata,name='hydraulicdata'),
    path('hydraulic_data_view/<int:wellphase_id>/',views.hydraulic_data_view,name='hydraulic_data_view'),
    path('import_hydraulic_data/<int:wellphase_id>/',views.import_hydraulic_data,name='import_hydraulic_data'),
    path('downloadcsv/<int:wellphase_id>/',views.downloadcsv,name='downloadcsv'),
    path('edit_hydraulic_data/<int:wellphase_id>/',views.edit_hydraulic_data,name='edit_hydraulic_data'),
    path('hydraulic_data_delete/<int:wellphase_id>/',views.hydraulic_data_delete,name='hydraulic_data_delete'),
    path('getrheogramrpm',views.getrheogramrpm,name='getrheogramrpm'),
    path('rheogramlist_actual/<int:wellphase_id>/', views.rheogramlist_actual, name='rheogramlist_actual'),
    path('rheogramcreate_actual/<int:wellphase_id>/', views.rheogramcreate_actual, name='rheogramcreate_actual'),
    path('rheogram_actual/<int:wellphase_id>/', views.rheogram_actual, name='rheogram_actual'),
    path('rheogramedit_actual/<int:wellphase_id>/', views.rheogramedit_actual, name='rheogramedit_actual'),
    path('importmuddata/<int:wellphase_id>/', views.importmuddata, name='importmuddata'),
    path('downloadmuddatacsv/<int:wellphase_id>/',views.downloadmuddatacsv,name='downloadmuddatacsv'),
    path('actual_well_view/<int:wellphase_id>/',views.actual_well_view,name='actual_well_view'),
    path('planfinal_data',views.planfinal_data,name='planfinal_data'),
    path('get_planwell_data',views.get_planwell_data,name='get_planwell_data'),
    path('addselected_data',views.addselected_data,name='addselected_data'),
    path('get_calculated_data',views.get_calculated_data,name='get_calculated_data'),
    path('chart_image',views.chart_image,name='chart_image'),
    path('actualwell_generate_report/<int:wellphase_id>/',views.actualwell_generate_report,name='actualwell_generate_report'),
    path('ecdalongwell_calculationincreased',views.ecdalongwell_calculationincreased,name='ecdalongwell_calculationincreased'),
    # path('get_all_unit',views.get_all_unit,name='get_all_unit'),


]
  