from django.urls import path
from . import views

app_name = 'bhadata'

urlpatterns = [
    
    path('<int:pk>/', views.details, name='detail'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('create/<int:wellphase_id>/', views.create, name='create'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('bhadatalist/<int:wellphase_id>/', views.bhadatalist, name='bhadatalist'),
    path('admindrillcollars/create', views.admindrillcollerscreate, name='admindrillcollerscreate'),
    path('admindrillcollars/view/', views.admindrillcollersdetails, name='admindrillcollersdetails'),
    path('admindrillcollers/edit', views.admindrillcollersedit, name='admindrillcollersedit'),
    path('admindrillcollers/delete/', views.admindrillcollersdelete, name='admindrillcollersdelete'),
    path('adminimportdata/', views.adminimportdata, name='adminimportdata'),
    path('download_csv_data/', views.download_csv_data, name='download_csv_data'),
    path('drillcollers/create', views.drillcollerscreate, name='drillcollerscreate'),
    path('drillcollers/view', views.drillcollersdetails, name='drillcollersview'),
    path('drillcollers/edit/', views.drillcollersedit, name='drillcollersedit'),
    path('drillcollers/delete', views.drillcollersdelete, name='drillcollersdelete'),
    path('masterimportdata/', views.masterimportdata, name='masterimportdata'),
    path('bhacaluculation',views.bhacaluculation,name='bhacaluculation'),
    path('bha_pipe_calc',views.bha_pipe_calc,name='bha_pipe_calc'),
    path('bha_Connectpipe_calc',views.bha_Connectpipe_calc,name='bha_Connectpipe_calc'),
    path('bha_tooljoint_calc',views.bha_tooljoint_calc,name='bha_tooljoint_calc'),
    path('bha_tooljoint_id_calc',views.bha_tooljoint_id_calc,name='bha_tooljoint_id_calc'),

    path('admindrillpipe/create/', views.admindrillpipecreate, name='admindrillpipecreate' ),
    path('admindrillpipe/view/', views.admindrillpipedetails, name='admindrillpipeview' ),
    path('admindrillpipe/edit/', views.admindrillpipeedit, name='admindrillpipeedit'),
    path('admindrillpipe/delete/', views.admindrillpipedelete, name='admindrillpipedelete'),
    path('adminpipeimportdata/', views.adminpipeimportdata, name='adminpipeimportdata' ),
    path('drillpipe/view',views.drillpipedetails,name='drillpipeview'),
    path('drillpipe/create/', views.drillpipecreate, name='drillpipecreate' ),
    path('drillpipe/edit/', views.drillpipeedit, name='drillpipeedit'),
    path('drillpipe/delete/', views.drillpipedelete, name='drillpipedelete'),
    path('pipe_download_csv_data/', views.pipe_download_csv_data, name='pipe_download_csv_data'),
    path('masterpipeimportdata/', views.masterpipeimportdata, name='masterpipeimportdata'),
    
    path('admindrillHWDP/create/', views.admindrillHWDPcreate, name='admindrillHWDPcreate'),
    path('admindrillHWDP/view/', views.admindrillHWDPdetails, name='admindrillHWDPview'),
    path('admindrillHWDP/edit/', views.admindrillHWDPedit, name='admindrillHWDPedit'),
    path('admindrillHWDP/delete/', views.admindrillHWDPdelete, name='admindrillHWDPdelete'),
    path('adminHWDPimportdata/', views.adminHWDPimportdata, name='adminHWDPimportdata'),
    path('drillHWDP/view',views.drillHWDPdetails,name='drillHWDPview'),
    path('drillHWDP/create/', views.drillHWDPcreate, name='drillHWDPcreate'),
    path('drillHWDP/edit/', views.drillHWDPedit, name='drillHWDPedit'),
    path('drillHWDP/delete/', views.drillHWDPdelete, name='drillHWDPdelete'),
    path('HWDP_download_csv_data/', views.HWDP_download_csv_data, name='HWDP_download_csv_data'),
    path('HWDPimportdata/', views.HWDPimportdata, name='HWDPimportdata'),
    # path('admindrillcollars', views.admindrillcollersindex, name='admindrillcollersindex'),
    path('getweight_drillpipe',views.getweight_drillpipe,name='getweight_drillpipe'),
    path('getgrade_drillpipe',views.getgrade_drillpipe,name='getgrade_drillpipe'),
    path('getjointtype_drillpipe',views.getjointtype_drillpipe,name='getjointtype_drillpipe'),
    path('getjointod_drillpipe',views.getjointod_drillpipe,name='getjointod_drillpipe'),
    path('getclass_drillpipe',views.getclass_drillpipe,name='getclass_drillpipe'),
    path('getweight_hwdpnod',views.getweight_hwdpnod,name='getweight_hwdpnod'),
    path('getjointtype_hwdp',views.getjointtype_hwdp,name='getjointtype_hwdp'),
    path('getjointod_hwdp',views.getjointod_hwdp,name='getjointod_hwdp'),
    path('getclass_hwdp',views.getclass_hwdp,name='getclass_hwdp'),
    path('getdrillcollordetails',views.getdrillcollordetails,name='getdrillcollordetails'),
    path('getmud',views.getmud,name='getmud'),
    path('getbhadata',views.getbhadata,name='getbhadata'),
    path('getrheogram',views.getrheogram,name='getrheogram'),
    path('getdrillbitdata',views.getdrillbitdata,name='getdrillbitdata'),
    path('getwellphase',views.getwellphase,name='getwellphase'),
    path('testphase/<int:well_id>/',views.testphase,name='testphase'),
    path('getpremium_val',views.getpremium_val,name='getpremium_val'),
    path('box_pin_tooljoint',views.box_pin_tooljoint,name='box_pin_tooljoint'),
    path('getempiricaldata',views.getempiricaldata,name='getempiricaldata'),
    path('getdifferential_Pressure',views.getdifferential_Pressure,name='getdifferential_Pressure'),
    path('getmdtvd_for_selecteddate',views.getmdtvd_for_selecteddate,name='getmdtvd_for_selecteddate'),
    path('editbha_actual',views.editbha_actual,name='editbha_actual'),
    path('deletebha_actual/<int:wellphase_id>/',views.deletebha_actual,name='deletebha_actual'),
    path('download_xls_data/<int:well_id>/',views.download_xls_data,name='download_xls_data'),
    path('importbha_actual/<int:wellphase_id>/', views.importbha_actual, name='importbha_actual' ),

   
]