"""
Django settings for hydraulics project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see

https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""


from pathlib import Path
import os


# import sentry_sdk
# from sentry_sdk.integrations.django import DjangoIntegration

# sentry_sdk.init(
#     dsn="https://e4a0f655aeaf4e798eac195931a33b19@o1024884.ingest.sentry.io/5990758",
#     integrations=[DjangoIntegration()],

#     # Set traces_sample_rate to 1.0 to capture 100%
#     # of transactions for performance monitoring.
#     # We recommend adjusting this value in production.
#     traces_sample_rate=1.0,

#     # If you wish to associate users to errors (assuming you are using
#     # django.contrib.auth) you may enable sending PII data.
#     send_default_pii=True
# )
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ulpdx7ilqopgkqmjet(e1hae@z+t1p^wz-w-p!e$f#*%qv&d9x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG=True


ALLOWED_HOSTS = ['*']
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', 
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
    'channels',
    'django.contrib.humanize',
    'custom_auth',
    'notifications',
    'crispy_forms',
    'projects',
    'wells',
    'mud',
    'surfacepipe',
    'pressure',
    'wellphases',
    'welltrajectory',
    'muddata',
    'drillbitdata',
    'bhadata',
    'rig',
    'widget_tweaks',
    'rest_framework',
    'pressureloss',
    'ticket',
    'license',
    'userlog',
   
]
ASGI_APPLICATION = "hydraulics.asgi.application"


# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer',
#     },
# }

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            #"hosts": [('143.1.1.122',8004)],
             "hosts": [('redis.mo.vc',8082)],
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'hydraulics.middlewares.tenant_middleware',
]

ROOT_URLCONF = 'hydraulics.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hydraulics.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR,"hydraulics/static")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

MEDIA_URL = '/media/'
MEDIA_ROOT  = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'custom_auth.User'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "developer1@xmedia.in"
# EMAIL_HOST_PASSWORD = "E8QPv/=X"
EMAIL_HOST_USER = "ibytesvc@gmail.com"
EMAIL_HOST_PASSWORD = "lufrlhyjedbistfa"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


DJANGO_NOTIFICATIONS_CONFIG = { 'USE_JSONFIELD': True}
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

STRIPE_PUBLIC_KEY = 'pk_test_51NITPcSI05wiMnGCG1DLZ3BrId9aEM4aWjbJKCaYyNc4MYk1aEal8FsS4MAssDCWiOLURl9Rfz8HprVT55ID7KMU00a31AR00s'
STRIPE_SECRET_KEY = 'sk_test_51NITPcSI05wiMnGCe09Xkucl8WUu5XsptMR6GkIKg9bN9bZUATiAigCOcNk1lwBVJMj3W39oP0vm0lym0YoSHygz002iDWquWt'
STRIPE_DEFAULT_CURRENCY = 'inr'
